var dbraw = [
  [
    [ "Inception", 
      [ "budget", "$USD237 million", "<http://dbpedia.org/property/budget>" ], 
      [ "cinematography", "Wally Pfister", "<http://dbpedia.org/property/cinematography>" ], 
      [ "comment", "Inception is a 2010 science fiction action heist film...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "Christopher Nolan", "<http://dbpedia.org/ontology/director>" ], 
      [ "distributor", "Warner Bros.", "<http://dbpedia.org/ontology/distributor>" ], 
      [ "editing", "Lee Smith (editor)", "<http://dbpedia.org/ontology/editing>" ], 
      [ "gross", "$2,782,275,172", "<http://dbpedia.org/property/gross>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "Hans Zimmer", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Christopher Nolan, Emma Thomas", "<http://dbpedia.org/ontology/producer>" ], 
      [ "runtime", "148 minutes", "<http://dbpedia.org/ontology/Work/runtime>" ], 
      [ "starring", "Cillian Murphy, Dileep Rao, Ellen Page, Joseph Gordon-...", "<http://dbpedia.org/property/starring>" ], 
      [ "studio", "Legendary Pictures, Syncopy Films", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "2010 films, 2010s science fiction films, American ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "Inception", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Creative Work, Film, Movie, Thing, Work", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "writer", "Christopher Nolan", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "The Lion King", 
      [ "budget", "$45 million", "<http://dbpedia.org/property/budget>" ], 
      [ "comment", "The Lion King is a 1994 American animated musical ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "starring", "James Earl Jones, Jeremy Irons, Matthew Broderick", "<http://dbpedia.org/ontology/starring>" ],
      [ "distributor", "Walt Disney Pictures", "<http://dbpedia.org/ontology/distributor>" ], 
      [ "editing", "Ivan Bilancio", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$951,583,777", "<http://dbpedia.org/property/gross>" ], 
      [ "label", "The Lion King", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "Hans Zimmer", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Don Hahn", "<http://dbpedia.org/ontology/producer>" ], 
      [ "runtime", "87 minutes", "<http://dbpedia.org/property/runtime>" ], 
      [ "studio", "Walt Disney Animation Studios", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "1990s adventure films, 1994 films, American animated ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1990s Adventure Films, 1994Films, American Animated ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Shrek", 
      [ "budget", "$60 million", "<http://dbpedia.org/property/budget>" ], 
      [ "comment", "Shrek is a 2001 American computer-animated fantasy-com...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "Andrew Adamson, Vicky Jenson", "<http://dbpedia.org/property/director>" ], 
      [ "distributor", "Dream Works, DreamWorks Pictures", "<http://dbpedia.org/ontology/distributor>" ], 
      [ "editing", "Sim Evan-Jones", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$484,409,218", "<http://dbpedia.org/ontology/gross>" ], 
      [ "label", "Shrek", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "Harry Gregson- Williams, John Powell", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Aron Warner, Jeffrey Katzenberg, John H. Williams", "<http://dbpedia.org/ontology/producer>" ], 
      [ "released", "2001", "<http://dbpedia.org/property/released>" ], 
      [ "runtime", "92 minutes", "<http://dbpedia.org/property/runtime>" ], 
      [ "starring", "Cameron Diaz, Eddie Murphy, John Lithgow, Mike Myers", "<http://dbpedia.org/property/starring>" ], 
      [ "studio", "Dream Works Animation, Pacific Data Images", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "2000s action films, 2000s adventure films, 2000s comedy...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "2001Films, American Animated Films, American ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Titanic", 
      [ "budget", "$200 million", "<http://dbpedia.org/property/budget>" ], 
      [ "cinematography", "Russell Carpenter", "<http://dbpedia.org/ontology/cinematography>" ], 
      [ "comment", "Titanic is a 1997 American epic romantic disaster film...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "James Cameron", "<http://dbpedia.org/property/director>" ], 
      [ "gross", "$2.187 billion", "<http://dbpedia.org/ontology/gross>" ], 
      [ "starring", "Leonardo DiCaprio, Kate Winslett, Billy Zane", "<http://dbpedia.org/property/starring>" ],
      [ "label", "Titanic", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "James Horner", "<http://dbpedia.org/property/music>" ], 
      [ "runtime", "194 minutes", "<http://dbpedia.org/property/runtime>" ], 
      [ "subject", "1990s romance films, 1997 films, 2010s 3D films, 20th ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "studio", "20th Century Fox, Paramount Pictures", "<http://dbpedia.org/property/studio>" ], 
      [ "title", "Titanic", "<http://dbpedia.org/property/title>" ], 
      [ "type", "1997 Films, 20th Century Fox Films, American Disaster ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "James Cameron", "<http://dbpedia.org/property/writer>" ], 
    ],
    [ "Up", 
      [ "budget", "$175 million", "<http://dbpedia.org/property/budget>" ], 
      [ "cinematography", "Jean-Claudie Kalache, Patrick Lin", "<http://dbpedia.org/property/cinematography>" ], 
      [ "comment", "Up is a 2009 American computer-animated comedy-...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "Pete Docter", "<http://dbpedia.org/ontology/director>" ], 
      [ "distributor", "Walt Disney Pictures", "<http://dbpedia.org/property/distributor>" ], 
      [ "editing", "Kevin Nolting", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$731,342,744", "<http://dbpedia.org/property/gross>" ], 
      [ "label", "Up", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "Michael Giacchino", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Jonas Rivera", "<http://dbpedia.org/property/producer>" ], 
      [ "released", "2009", "<http://dbpedia.org/property/released>" ], 
      [ "runtime", "96 minutes", "<http://dbpedia.org/ontology/runtime>" ], 
      [ "story", "Bob Peterson, Pete Docter, Thomas Mc Carthy (entertainer)", "<http://dbpedia.org/property/story>" ], 
      [ "studio", "Pixar", "<http://dbpedia.org/property/studio>" ], 
      [ "type", "2000s Adventure Films, 2000s Comedy Films, 2009Films ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "Bob Peterson (animator), Pete Docter", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "Finding Nemo", 
      [ "budget", "$94 million", "<http://dbpedia.org/ontology/budget>" ], 
      [ "cinematography", "Jeremy Lasky, Sharon Calahan", "<http://dbpedia.org/property/cinematography>" ], 
      [ "comment", "Finding Nemo is an animated film about a clown fish ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "Andrew Stanton", "<http://dbpedia.org/ontology/director>" ], 
      [ "distributor", "Walt Disney Pictures", "<http://dbpedia.org/ontology/distributor>" ], 
      [ "editing", "David Ian Salter", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$921,743,261", "<http://dbpedia.org/property/gross>" ], 
      [ "label", "Finding Nemo", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "length", "100 minutes", "<http://dbpedia.org/property/length>" ], 
      [ "music", "Thomas Newman", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Graham Walters, Thomas Newman, Bill Bernstein", "<http://dbpedia.org/property/producer>" ], 
      [ "released", "2003-05-20", "<http://dbpedia.org/property/released>" ], 
      [ "starring", "Albert Brooks, Alexander Gould, Ellen De Generes", "<http://dbpedia.org/ontology/starring>" ], 
      [ "story", "Andrew Stanton", "<http://dbpedia.org/property/story>" ], 
      [ "studio", "Pixar", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "2003 films, American animated films, American ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "2003Films, American Animated Films, American ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "Andrew Stanton, Bob Peterson (animator), David Reynolds", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "The Dark Knight", 
      [ "budget", "$185 million", "<http://dbpedia.org/ontology/budget>" ], 
      [ "comment", "The Dark Knight is a 2008 superhero film directed, prod...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United States", "<http://dbpedia.org/property/country>" ], 
      [ "director", "Christopher Nolan", "<http://dbpedia.org/property/director>" ], 
      [ "distributor", "Warner Bros.", "<http://dbpedia.org/property/distributor>" ], 
      [ "editing", "Lee Smith (editor)", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$1,004,558,444", "<http://dbpedia.org/ontology/gross>" ], 
      [ "label", "The Dark Knight (film)", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music Composer", "Hans Zimmer, James Newton Howard", "<http://dbpedia.org/ontology/musicComposer>" ], 
      [ "producer", "Charles Roven, Christopher Nolan, Emma Thomas", "<http://dbpedia.org/property/producer>" ], 
      [ "runtime", "152 minutes", "<http://dbpedia.org/ontology/Work/runtime>" ], 
      [ "screenplay", "Christopher Nolan, Jonathan Nolan", "<http://dbpedia.org/property/screenplay>" ], 
      [ "starring", "Aaron Eckhart, Christian Bale, Gary Oldman, Heath Led...", "<http://dbpedia.org/ontology/starring>" ], 
      [ "story", "Christopher Nolan, David S. Goyer", "<http://dbpedia.org/property/story>" ], 
      [ "studio", "DC Comics, Legendary Pictures, Syncopy Films", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "2000s action films, 2008 films, American action films...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "2000s Action Films, 2008Films, American Action Films, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "Christopher Nolan, Jonathan Nolan", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "Star Wars Episode IV: A New Hope", 
      [ "budget", "$11 million", "<http://dbpedia.org/property/budget>" ], 
      [ "cinematography", "British Society of Cinematographers, Gilbert Taylor", "<http://dbpedia.org/property/cinematography>" ], 
      [ "comment", "Star Wars Episode IV: A New Hope, originally released ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "George Lucas", "<http://dbpedia.org/ontology/director>" ], 
      [ "distributor", "20th Century Fox", "<http://dbpedia.org/property/distributor>" ], 
      [ "editing", "Marcia Lucas, Paul Hirsch (film editor), Richard Chew", "<http://dbpedia.org/property/editing>" ], 
      [ "gross", "$775,398,007", "<http://dbpedia.org/property/gross>" ], 
      [ "label", "Star Wars Episode IV: A New Hope", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "John Williams", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Gary Kurtz", "<http://dbpedia.org/ontology/producer>" ], 
      [ "runtime", "121 minutes", "<http://dbpedia.org/ontology/Work/runtime>" ], 
      [ "starring", "Alec Guinness, Carrie Fisher, Harrison Ford, Mark...", "<http://dbpedia.org/ontology/starring>" ], 
      [ "studio", "Lucasfilm", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "1970s science fiction films, 1977 films, 20th Century...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "Star Wars Episode IV: A New Hope", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Creative Work, Film, Movie, Movie CW, Thing, Work", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "George Lucas", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "Jurassic Park", 
      [ "budget", "$63 million", "<http://dbpedia.org/ontology/budget>" ], 
      [ "cinematography", "Dean Cundey", "<http://dbpedia.org/ontology/cinematography>" ], 
      [ "comment", "Jurassic Park is a 1993 American science fiction adven...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "Steven Spielberg", "<http://dbpedia.org/ontology/director>" ], 
      [ "distributor", "Universal Studios", "<http://dbpedia.org/ontology/distributor>" ], 
      [ "editing", "Michael Kahn (film editor)", "<http://dbpedia.org/ontology/editing>" ], 
      [ "gross", "$1,029,153,882", "<http://dbpedia.org/ontology/gross>" ], 
      [ "language", "English, Spanish", "<http://dbpedia.org/property/language>" ], 
      [ "music", "John Williams", "<http://dbpedia.org/property/music>" ], 
      [ "producer", "Gerald R. Molen, Kathleen Kennedy, Steven Sp...", "<http://dbpedia.org/property/producer>" ], 
      [ "runtime", "127 minutes", "<http://dbpedia.org/ontology/Work/runtime>" ], 
      [ "screenplay", "David Koepp, Michael Crichton", "<http://dbpedia.org/property/screenplay>" ], 
      [ "starring", "Ariana Richards, Bob Peck, Jeff Goldblum, Joseph...", "<http://dbpedia.org/ontology/starring>" ], 
      [ "studio", "Amblin Entertainment", "<http://dbpedia.org/property/studio>" ], 
      [ "subject", "1990s adventure films, 1990s science fiction films ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "Jurassic Park", "<http://dbpedia.org/property/title>" ], 
      [ "type", "1990s Adventure Films, 1990s Science Fiction Films, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "writer", "David Koepp, Michael Crichton", "<http://dbpedia.org/ontology/writer>" ], 
    ],
    [ "Avatar", 
      [ "budget", "$237 million", "<http://dbpedia.org/property/budget>" ], 
      [ "cinematography", "Mauro Fiore", "<http://dbpedia.org/property/cinematography>" ], 
      [ "comment", "Avatar is a 2009 American epic science fiction film ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "director", "James Cameron", "<http://dbpedia.org/property/director>" ], 
      [ "distributor", "20th Century Fox", "<http://dbpedia.org/property/distributor>" ], 
      [ "gross", "$2,782,275,172", "<http://dbpedia.org/ontology/gross>" ], 
      [ "label", "Avatar", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "starring", "Sam Worthington, Zoe Saldana, Stephen Lang", "<http://dbpedia.org/ontology/starring>" ],
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "music", "James Horner", "<http://dbpedia.org/property/music>" ], 
      [ "runtime", "162 minutes", "<http://dbpedia.org/property/runtime>" ], 
      [ "subject", "2000s 3D films, 2000s science fiction films, 2009 ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "2000s Science Fiction Films, 2009Films, 20th Century ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ],
      [ "wordnet type", "synset-movie-noun-1", "<http://dbpedia.org/property/wordnet_type>" ],  
      [ "writer", "James Cameron", "<http://dbpedia.org/ontology/writer>" ], 
    ],
  ],
  [
    [ "Battle of Gaugamela", 
      [ "casualties", "100, 300, 300000, 40000, 47000, 500, 90000, ;", "<http://dbpedia.org/property/casualties>" ], 
      [ "causalties", "(according to Arrian), (according to Curtius Rufus), ...", "<http://dbpedia.org/ontology/causalties>" ], 
      [ "combatant", "Achaemenid Empire, Achaemenid Empire, Greek mercen...", "<http://dbpedia.org/property/combatant>" ], 
      [ "commander", "Alexander the Great, Antigonus, Bessus, Bessus, ...", "<http://dbpedia.org/property/commander>" ], 
      [ "comment", "The Battle of Gaugamela took place in 331 BC between...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "conflict", "Battle of Gaugamela", "<http://dbpedia.org/property/conflict>" ], 
      [ "geometry", "POINT(43.25 36.36)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "is part of", "Wars of Alexander the Great", "<http://dbpedia.org/ontology/isPartOf>" ], 
      [ "label", "Battle of Gaugamela", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "lat", "36.36", "<http://www.w3.org/2003/01/geo/wgs84_pos#lat>" ], 
      [ "long", "43.25", "<http://www.w3.org/2003/01/geo/wgs84_pos#long>" ], 
      [ "point", "36.36 43.25", "<http://www.georss.org/georss/point>" ], 
      [ "result", "Decisive Greek victory, Persian military capabilities ...", "<http://dbpedia.org/ontology/result>" ], 
      [ "strengths", "220,000-250,000", "<http://dbpedia.org/ontology/strengths>" ], 
      [ "subject", "331 BC, Arbil, Battles involving the Achaemenid Empire, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Battles Involving The Achaemenid Empire, Battles Of Alex...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-war-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Battle of Chosin Reservoir", 
      [ "causalties", "1,029 killed, 13,900, 15 tank losses, 4,582 wounded, ...", "<http://dbpedia.org/ontology/causalties>" ], 
      [ "commander", "Douglas Mac Arthur, Douglas MacArthur, Edward Almond, ...", "<http://dbpedia.org/ontology/commander>" ], 
      [ "comment", "The Battle of Chosin Reservoir, also known as the Chosin...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "conflict", "Battle of Chosin Reservoir", "<http://dbpedia.org/property/conflict>" ], 
      [ "date", "1950-12-13, 27", "<http://dbpedia.org/ontology/date>" ], 
      [ "geometry", "POINT(127.2 40.4833)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "is part of", "Korean War", "<http://dbpedia.org/ontology/ispartof>" ], 
      [ "label", "Battle of Chosin Reservoir", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "lat", "40.4833", "<http://www.w3.org/2003/01/geo/wgs84_pos#lat>" ], 
      [ "long", "127.2", "<http://www.w3.org/2003/01/geo/wgs84_pos#long>" ], 
      [ "pinyin", "Chang Jin Hu Zhanyi", "<http://dbpedia.org/property/p>" ], 
      [ "place", "Battle of Chosin Reservoir, Changjin, Chosin Reservoir, ...", "<http://dbpedia.org/ontology/place>" ], 
      [ "point", "40.483333333333334 127.2", "<http://www.georss.org/georss/point>" ], 
      [ "result", "Chinese Pyrrhic victory", "<http://dbpedia.org/ontology/result>" ], 
      [ "strength", "Committed: ~30,000, Committed: ~67,000, Nominal: 103,520...", "<http://dbpedia.org/ontology/strength>" ], 
      [ "subject", "1950 in Korea, Battles involving South Korea, Battles of ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Battles Involving China, Battles Involving Korea, Bat...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "units", "20th Corps, 26th Corps, 27th Corps, 1, 9, X Corps", "<http://dbpedia.org/property/units>" ], 
      [ "wordnet type", "synset-war-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Assassination of Julius Caesar", 
      [ "comment", "The assassination of Julius Caesar was the result of a ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "label", "Assassination of Julius Caesar", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "date", "15 March, 44 BCE", "<http://dbpedia.org/ontology/date>" ],
      [ "casualties", "One (Julius Caesar)", "<http://dbpedia.org/ontology/casualties>" ],
      [ "place", "City of Rome", "<http://dbpedia.org/ontology/place>" ],
      [ "subject", "44 BC crimes, Assassinations, Julius Caesar, Roman Republic", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "44 BC Crimes, Assassinations", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "cause", "Fear of return to absolute monarchy in Rome", "<http://dbpedia.org/ontology/cause>" ],
      [ "title", "Assassination of Julius Caesar", "<http://dbpedia.org/ontology/title>" ],
      [ "result", "Liberator's Civil War", "<http://dbpedia.org/ontology/result>" ], 
      [ "location", "Roman senate", "<http://dbpedia.org/ontology/result>" ],
      [ "participants", "Julius Caesar, Marcus Junius Brutus, Gaius Cassius Longinus", "<http://dbpedia.org/ontology/participants>" ],
    ],
    [ "Signing of the Treaty of Waitangi", 
      [ "comment", "The Treaty of Waitangi is a treaty first signed on 6 Feb...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "date Drafted", "45", "<http://dbpedia.org/property/dateDrafted>" ], 
      [ "date Signed", "6 Feb 1840", "<http://dbpedia.org/property/dateSigned>" ], 
      [ "label", "Te Tiriti o Waitangi, Treaty of Waitangi", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "languages", "English, Maori", "<http://dbpedia.org/property/languages>" ], 
      [ "location Signed", "Waitangi, Bay of Islands, New Zealand and various ...", "<http://dbpedia.org/property/locationSigned>" ], 
      [ "long Name", "Treaty to establish a British Governor of New Zealand, ...", "<http://dbpedia.org/property/longName>" ], 
      [ "signatories", "500 Maori chiefs, representatives of British Crown", "<http://dbpedia.org/property/signatories>" ], 
      [ "subject", "1840 in New Zealand, 1840 treaties, Aboriginal title in ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1840 Treaties, Race Relations In New Zealand", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Charge of the Light Brigade", 
      [ "casualties", "270", "<http://dbpedia.org/property/casualties>" ], 
      [ "causalties", "270+", "<http://dbpedia.org/ontology/causalties>" ], 
      [ "commander", "Pavel Liprandi", "<http://dbpedia.org/property/commander>" ], 
      [ "comment", "The Charge of the Light Brigade was a charge of British ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "conflict", "Charge of the Light Brigade", "<http://dbpedia.org/property/conflict>" ], 
      [ "date", "1854-10-25, 25", "<http://dbpedia.org/ontology/date>" ], 
      [ "geometry", "POINT(33.6242 44.5378)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "is part of", "Battle of Balaclava, Crimean War", "<http://dbpedia.org/ontology/isPartOf>" ], 
      [ "label", "Charge of the Light Brigade", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "lat", "44.5378", "<http://www.w3.org/2003/01/geo/wgs84_pos#lat>" ], 
      [ "long", "33.6242", "<http://www.w3.org/2003/01/geo/wgs84_pos#long>" ], 
      [ "point", "44.53777777777778 33.62416666666667", "<http://www.georss.org/georss/point>" ], 
      [ "result", "Russian victory", "<http://dbpedia.org/property/result>" ], 
      [ "strength", "670, 670+", "<http://dbpedia.org/property/strength>" ], 
      [ "subject", "19th-century history of the British Army, Cavalry ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Conflicts In 1854, Event, Feature, Thing", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Battle of Antietam", 
      [ "casualties", "10316, 12401", "<http://dbpedia.org/property/casualties>" ], 
      [ "causalties", "12,401 (2,108 killed, 753 captured/missing), 9,540 wounded", "<http://dbpedia.org/ontology/causalties>" ], 
      [ "combatant", "(Union)", "<http://dbpedia.org/ontology/combatant>" ], 
      [ "commander", "George B. Mc Clellan, Robert E. Lee", "<http://dbpedia.org/ontology/commander>" ], 
      [ "comment", "The Battle of Antietam also known as the Battle of Sharps...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "conflict", "Battle of Antietam", "<http://dbpedia.org/property/conflict>" ], 
      [ "date", "1862-09-17", "<http://dbpedia.org/property/date>" ], 
      [ "is Part Of", "American Civil War", "<http://dbpedia.org/ontology/isPartOfMilitaryConflict>" ], 
      [ "label", "Battle of Antietam", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "lat", "39.4732", "<http://www.w3.org/2003/01/geo/wgs84_pos#lat>" ], 
      [ "long", "-77.7447", "<http://www.w3.org/2003/01/geo/wgs84_pos#long>" ], 
      [ "place", "Near Sharpsburg, Maryland, Sharpsburg, Maryland", "<http://dbpedia.org/property/place>" ], 
      [ "point", "39.4732 -77.7447", "<http://www.georss.org/georss/point>" ], 
      [ "result", "Tactically inconclusive; strategic Union victory", "<http://dbpedia.org/ontology/result>" ],
      [ "strength", "38,000 engaged, 75,500 present for duty", "<http://dbpedia.org/ontology/strength>" ], 
      [ "subject", "1862 in Maryland, 1862 in the United States, Battles of...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Battles Of The Main Eastern Theater Of The American Civ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-war-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Storming of the Bastille", 
      [ "causalties", "one (six or possibly eight killed after surrender)", "<http://dbpedia.org/ontology/causalties>" ], 
      [ "combatant", "Parisian militia", "<http://dbpedia.org/property/combatant>" ], 
      [ "commander", "Bernard-Rene de Launay, ...", "<http://dbpedia.org/ontology/commander>" ], 
      [ "comment", "The storming of the Bastille occurred in Paris, France...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "conflict", "The storming of the Bastille", "<http://dbpedia.org/property/conflict>" ], 
      [ "date", "1789-07-14", "<http://dbpedia.org/property/date>" ], 
      [ "is part of", "French Revolution", "<http://dbpedia.org/ontology/isPartOf>" ], 
      [ "label", "Storming of the Bastille", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "place", "Paris, France", "<http://dbpedia.org/ontology/place>" ], 
      [ "result", "Bastille captured, rebellion begins", "<http://dbpedia.org/property/result>" ], 
      [ "strength", "114 soldiers, 30 artillery pieces, 600, ...", "<http://dbpedia.org/ontology/strength>" ], 
      [ "subject", "1789 events of the French Revolution, History of Paris", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1789 Events Of The French Revolution, Conflict Event, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-war-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "The First Moon landing", 
      [ "comment", "A moon landing is the arrival of a spacecraft on the ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "label", "Moon landing", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "subject", "Exploration of the Moon, History of television", "<http://purl.org/dc/terms/subject>" ], 
      [ "participants", "Neil Armstrong, Buzz Aldrin, Michael Collins", "<http://dbpedia.org/ontology/participants>" ],
      [ "result", "first human exploration of extraterrestial body", "<http://dbpedia.org/ontology/result>" ],
      [ "date", "July 4, 1969", "<http://dbpedia/ontoology/date" ],
      [ "is part of", "exploration of space", "<http://dbpedia.org/ontology/ispartof>" ],
      [ "place", "The moon of Earth", "<http://dbpedia.org/ontology/place>" ],
      [ "wordnet type", "synset-space-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Magna Carta", 
      [ "comment", "Magna Carta, also called Magna Carta Libertatum or The ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "date", "1215", "<http://dbpedia.org/property/dateCreated>" ], 
      [ "document Name", "Magna Carta", "<http://dbpedia.org/property/documentName>" ], 
      [ "label", "Magna Carta", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "DocLocation", "Various copies", "<http://dbpedia.org/property/locationOfDocument>" ], 
      [ "subject", "1210s in England, 1215 in Europe, 1215 in law, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "Magna Carta 1297", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Barons Wars, British Library Collections, Constitu...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "writer", "Barons of King John of England", "<http://dbpedia.org/property/writer>" ], 
      [ "result", "Increased freedom for English nobles", "<http://dbpedia.org/ontological/result>" ],
    ],
    [ "Universal Declaration of Human Rights", 
      [ "comment", "The Universal Declaration of Human Rights (UDHR) is ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "date Created", "1948", "<http://dbpedia.org/property/dateCreated>" ], 
      [ "date Ratified", "10", "<http://dbpedia.org/property/dateRatified>" ], 
      [ "description", "--01-06", "<http://dbpedia.org/property/description>" ], 
      [ "document Name", "Universal Declaration of Human Rights", "<http://dbpedia.org/property/documentName>" ], 
      [ "label", "Universal Declaration of Human Rights", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "DocLocation", "Palais de Chaillot, Paris", "<http://dbpedia.org/property/locationOfDocument>" ], 
      [ "purpose", "Human rights", "<http://dbpedia.org/property/purpose>" ], 
      [ "subject", "1948 in law, History of human rights, Human rights, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "State of the Union", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Document106470073, Human Rights, United Nations General ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "writer", "John Peters Humphrey, Rene Cassin, Stephane Hess...", "<http://dbpedia.org/property/writer>" ], 
    ],
  ],
  [
    [ "Winston Churchill", 
      [ "alma Mater", "Harrow School, Royal Military Academy Sandhurst", "<http://dbpedia.org/property/almaMater>" ], 
      [ "alternative Names", "Sir Winston Leonard Spencer Churchill, The Rt Hon. ...", "<http://dbpedia.org/property/alternativeNames>" ], 
      [ "birth Date", "1874-11-30", "<http://dbpedia.org/ontology/birthDate>" ], 
      [ "birthname", "Winston Leonard Spencer-Churchill", "<http://dbpedia.org/property/birthname>" ], 
      [ "branch", "British Army", "<http://dbpedia.org/property/branch>" ], 
      [ "comment", "Sir Winston Leonard Spencer-Churchill, KG, OM, CH, TD, ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "British Empire", "<http://dbpedia.org/ontology/country>" ], 
      [ "death Date", "1965-01-24", "<http://dbpedia.org/property/deathDate>" ], 
      [ "description", "English statesman and author, best known as Prime Min ...", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "label", "Winston Churchill", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "military Branch", "British Army", "<http://dbpedia.org/ontology/militaryBranch>" ], 
      [ "nationality", "English", "<http://dbpedia.org/property/nationality>" ], 
      [ "order In Office", "Chancellor of the Exchequer, Home Secretary, Leader ...", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "profession", "Member of Parliament, statesman, soldier, journal...", "<http://dbpedia.org/property/profession>" ], 
      [ "religion", "Anglicanism", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "English statesman and author, best known as Prime...", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "Sir Winston Churchill signature.svg", "<http://dbpedia.org/property/signature>" ], 
      [ "subject", "1874 births, 1965 deaths, 4th Queen's Own Hussars ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "surname", "Churchill", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Chancellor of the Duchy of Lancaster, Chancellor of the...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "4th Queen's Own Hussars Officers, Agent, British ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-chancellor-noun-1, synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Gordon Brown", 
      [ "alma Mater", "University of Edinburgh", "<http://dbpedia.org/ontology/almaMater>" ], 
      [ "alternative Names", "Brown, Gordon", "<http://dbpedia.org/property/alternativeNames>" ], 
      [ "birth Date", "1951-02-20", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "James Gordon Brown (born 20 February 1951) is a Brit...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "British politician", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "label", "Gordon Brown", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "leader", "John Smith (Labour Party leader), Margaret Beckett, ...", "<http://dbpedia.org/property/leader>" ], 
      [ "office", "Chancellor of the Exchequer, Department for Business, ...", "<http://dbpedia.org/ontology/office>" ], 
      [ "order In Office", "Prime Minister of the United Kingdom", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "Scottish Labour Party", "<http://dbpedia.org/ontology/party>" ], 
      [ "religion", "Church of Scotland", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "British politician", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "Signature of Gordon Brown.png", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Sarah Brown", "<http://dbpedia.org/property/spouse>" ], 
      [ "subject", "1951 births, Academics of Glasgow Caledonian University, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "surname", "Brown", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Chancellor of the Exchequer, Department for Business, ...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Academics Of Glasgow Caledonian University, Academics Of ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-chancellor-noun-1, synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Jenny Shipley", 
      [ "birth Date", "1952-02-04", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "Dame Jenny Shipley, DNZM (born 4 February 1952), served ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "New Zealand", "<http://dbpedia.org/ontology/country>" ], 
      [ "description", "Prime Minister of New Zealand, politician, teacher", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "label", "Jenny Shipley", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "office", "28th Leader of the Opposition", "<http://dbpedia.org/property/office>" ], 
      [ "order In Office", "36th Prime Minister of New Zealand", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "parliament", "New Zealand", "<http://dbpedia.org/property/parliament>" ], 
      [ "party", "New Zealand National Party", "<http://dbpedia.org/property/party>" ], 
      [ "profession", "Teacher", "<http://dbpedia.org/property/profession>" ], 
      [ "religion", "Presbyterianism", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "Prime Minister of New Zealand, politician, teacher", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "spouse", "Burton Shipley", "<http://dbpedia.org/property/spouse>" ], 
      [ "subject", "1952 births, Dames Companion of the New Zealand Order of ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Bill English, Brian Connell, Constituency abolished, Hel...", "<http://dbpedia.org/ontology/successor>" ], 
      [ "surname", "Shipley", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Ashburton (New Zealand electorate), Leader of the Nation...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Female Heads Of Government, Leaders Of The Opposit...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Tony Blair", 
      [ "alma Mater", "Inns of Court School of Law, St John's College, Oxford", "<http://dbpedia.org/ontology/almaMater>" ], 
      [ "alternative Names", "Blair, Anthony Charles Lynton", "<http://dbpedia.org/property/alternativeNames>" ], 
      [ "birth Date", "1953-05-06", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "Anthony Charles Lynton Blair (born 6 May 1953) is a Brit...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "Politician; Former Prime minister of the United Kingdom", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "given Name", "Tony", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "hansard", "mr-tony-blair", "<http://dbpedia.org/property/hansard>" ], 
      [ "label", "Tony Blair", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order In Office", "Prime Minister of the United Kingdom", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "Labour Party (UK)", "<http://dbpedia.org/ontology/party>" ], 
      [ "religion", "Catholic Church", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "Politician; Former Prime minister of the United Kingdom", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "Signature of Tony Blair.png", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Cherie Blair, Cherie Booth", "<http://dbpedia.org/ontology/spouse>" ], 
      [ "subject", "1953 births, Alumni of St John's College, Oxford, Alumn...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Frank Dobson, Gordon Brown, Jack Straw, John Major, Phil ...", "<http://dbpedia.org/ontology/successor>" ], 
      [ "title", "Chairperson of the Group of 8, Department of Energy (Uni...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Alumni Of St John's College, Oxford, Alumni ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-chancellor-noun-1, synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "David Lange", 
      [ "birth Date", "1942-08-04", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "David Russell Lange, ONZ, CH, served as the 32nd Prime ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "death Date", "2005-08-13", "<http://dbpedia.org/property/deathDate>" ], 
      [ "description", "Prime Minister of New Zealand, politician, lawyer", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "electorate", "Mangere (New Zealand electorate)", "<http://dbpedia.org/property/electorate>" ], 
      [ "given Name", "David Russell", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "label", "David Russell Lange", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order", "23, 32", "<http://dbpedia.org/property/order>" ], 
      [ "order In Office", "23rd  Leader of the Opposition, 32nd Prime Minister ...", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "New Zealand Labour Party", "<http://dbpedia.org/ontology/party>" ], 
      [ "profession", "Lawyer", "<http://dbpedia.org/property/profession>" ], 
      [ "religion", "Methodism", "<http://dbpedia.org/property/religion>" ], 
      [ "short Description", "Prime Minister of New Zealand, politician, lawyer", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "spouse", "Margaret Pope, Naomi Joy Crampton", "<http://dbpedia.org/property/spouse>" ], 
      [ "subject", "1942 births, 2005 deaths, Attorneys General of...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Geoffrey Palmer (politician), Robert Muldoon, Taito Phil...", "<http://dbpedia.org/ontology/successor>" ], 
      [ "surname", "Lange", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Prime minister of New Zealand", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Attorneys General Of New Zealand, Leaders Of The...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Angela Merkel", 
      [ "alma Mater", "University of Leipzig", "<http://dbpedia.org/property/almaMater>" ], 
      [ "birth Date", "1954-07-17", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "Angela Dorothea Merkel, nee Kasner (born 17 July 1954)...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "German politician", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "given Name", "Angela", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "label", "Angela Merkel", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "office", "Chancellor of Germany, Federal Ministry for the Environ...", "<http://dbpedia.org/property/office>" ], 
      [ "order In Office", "Chancellor of Germany", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "other Party", "Democratic Awakening", "<http://dbpedia.org/ontology/otherParty>" ], 
      [ "party", "Christian Democratic Union, Christian Democratic Union ...", "<http://dbpedia.org/property/party>" ], 
      [ "religion", "Lutheranism", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "German politician", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "Angela Merkel Signature.svg", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Joachim Sauer, Ulrich Merkel", "<http://dbpedia.org/ontology/spouse>" ], 
      [ "subject", "1954 births, Chancellors of Germany, Charlemagne Prize...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Claudia Nolte, Jürgen Trittin", "<http://dbpedia.org/property/successor>" ], 
      [ "surname", "Merkel", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Chairperson of the Group of 8, Chancellor of...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Chancellor Head Of Government, Christian Demo...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "John Howard", 
      [ "alma Mater", "University of Sydney", "<http://dbpedia.org/property/almaMater>" ], 
      [ "birth Date", "1939-07-26", "<http://dbpedia.org/ontology/birthDate>" ], 
      [ "comment", "John Winston Howard, OM, AC, SSI, (born 26 July 1939) ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "Prime Minister of Australia", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "given Name", "John Winston", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "label", "John Winston Howard", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "office", "22, 22nd Leader of the Opposition, 25, 29, 29th Treasurer...", "<http://dbpedia.org/property/office>" ], 
      [ "order In Office", "25th Prime Minister of Australia, Elections: 1996 ...", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "other Party", "Coalition (Australia)", "<http://dbpedia.org/ontology/otherParty>" ], 
      [ "otherparty", "Coalition (Australia)", "<http://dbpedia.org/property/otherparty>" ], 
      [ "parliament", "Australian", "<http://dbpedia.org/property/parliament>" ], 
      [ "party", "Liberal Party of Australia", "<http://dbpedia.org/property/party>" ], 
      [ "short Description", "Prime Minister of Australia", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "John Howard Signature.svg", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Janette Howard", "<http://dbpedia.org/ontology/spouse>" ], 
      [ "subject", "1939 births, Australian Anglicans, Australian Leaders ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Andrew Peacock, Kevin Rudd, Kim Beazley, Maxine McKew,...", "<http://dbpedia.org/property/successor>" ], 
      [ "surname", "Howard", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Commonwealth Chairperson-in- Office...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Australian Leaders Of The Opposition, Australian...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-chancellor-noun-1, synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Jacques Chirac", 
      [ "alma Mater", "Ecole nationale d'administration, Harvard Uni...", "<http://dbpedia.org/property/almaMater>" ], 
      [ "alternative Names", "Chirac, Jacques Rene", "<http://dbpedia.org/property/alternativeNames>" ], 
      [ "birth Date", "1932-11-29", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "Jacques Rene Chirac is a French politician who served a...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "President of France", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "given Name", "Jacques", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "label", "Jacques Chirac", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "office", "Co- Princes of Andorra, Co-Prince of Andorra, List...", "<http://dbpedia.org/property/office>" ], 
      [ "order In Office", "President of France", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "Communist Party, French Communist Party, Rally for the Re...", "<http://dbpedia.org/property/party>" ], 
      [ "religion", "Catholic Church", "<http://dbpedia.org/ontology/religion>" ], 
      [ "short Description", "President of France", "<http://dbpedia.org/property/shortDescription>" ], 
      [ "signature", "Jacques Chirac Signature.svg", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Bernadette Chirac, Bernadette de Courcel", "<http://dbpedia.org/ontology/spouse>" ], 
      [ "subject", "1932 births, Alumni of Sciences Po, Alumni of the École...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Jean Tiberi, Michel Poniatowski, Michel Rocard, Nicolas ...", "<http://dbpedia.org/property/successor>" ], 
      [ "surname", "Chirac", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Chairperson of the Group of 7, Chairperson of the Group ...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Office Holder, Person, Person With Occupation, Pol...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-incumbent-noun-1, synset-president-noun-3", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Nicolas Sarkozy", 
      [ "alma Mater", "Institut d'Etudes Politiques de Paris, Paris...", "<http://dbpedia.org/property/almaMater>" ], 
      [ "birth Date", "1955-01-28", "<http://dbpedia.org/property/birthDate>" ], 
      [ "comment", "Nicolas Sarkozy (born Nicolas Paul Stéphane Sárközy de...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "description", "23rd President of France from 16 May 2007 to 15 May...", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "given Name", "Nicolas", "<http://xmlns.com/foaf/0.1/givenName>" ], 
      [ "label", "Nicolas Sarkozy", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "office", "Co-Princes of Andorra, Co-Prince of Andorra, List of ...", "<http://dbpedia.org/property/office>" ], 
      [ "order In Office", "President of France", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "Rally for the Republic, Union for a Popular Movement", "<http://dbpedia.org/property/party>" ], 
      [ "signature", "Nicolas Sarkozy signature.svg", "<http://dbpedia.org/property/signature>" ], 
      [ "spouse", "Cecilia Attias, Cecilia Ciganer-Albeniz, Carl...", "<http://dbpedia.org/ontology/spouse>" ], 
      [ "subject", "1955 births, Alumni of Sciences Po, Candidates...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Dominique de Villepin, François Baroin, François H...", "<http://dbpedia.org/property/successor>" ], 
      [ "surname", "Sarkozy", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Acting, Co- Princes of Andorra, Honorary Canon...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Alumni Of Sciences Po, Current National Leaders, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "vice President", "Jean-Claude Gaudin", "<http://dbpedia.org/ontology/vicePresident>" ], 
      [ "wordnet type", "synset-incumbent-noun-1, synset-president-noun-3", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "Bob Hawke", 
      [ "alma Mater", "Australian National University, University College, ...", "<http://dbpedia.org/property/almaMater>" ], 
      [ "alternative Names", "Hawke, Robert James Lee", "<http://dbpedia.org/property/alternativeNames>" ], 
      [ "birth Date", "1929-12-09", "<http://dbpedia.org/ontology/birthDate>" ], 
      [ "comment", "Robert James Lee Hawke aka Bob Hawke is the 23rd Prime...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "constituency Mp", "Division of Wills", "<http://dbpedia.org/property/constituencyMp>" ], 
      [ "description", "23rd Prime Minister of Australia", "<http://purl.org/dc/elements/1.1/description>" ], 
      [ "label", "Bob Hawke", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order In Office", "23rd Prime Minister of Australia, Elections: 1983...", "<http://dbpedia.org/ontology/orderInOffice>" ], 
      [ "party", "Australian Labor Party", "<http://dbpedia.org/ontology/party>" ], 
      [ "spouse", "Blanche d'Alpuget, Hazel Hawke, ...", "<http://dbpedia.org/property/spouse>" ], 
      [ "subject", "1929 births, Alumni of University College, Oxford, Aust...", "<http://purl.org/dc/terms/subject>" ], 
      [ "successor", "Andrew Peacock, John Kerin, Paul Keating, Phil Cleary", "<http://dbpedia.org/ontology/successor>" ], 
      [ "surname", "Hawke", "<http://xmlns.com/foaf/0.1/surname>" ], 
      [ "title", "Leader of the Labor Party, List of Australian Leaders of...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Agent, Alumni Of University College, Oxford, Australian ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-chancellor-noun-1, synset-incumbent-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
  ],
  [
    [ "Walt Disney World Resort", 
      [ "comment", "The Walt Disney World Resort (also known informally as ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "geometry", "POINT(-81.5811 28.4186)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "Walt Disney World Resort", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "coordinates", "28deg 25min 7sec N,81deg 34min 52sec W", "<http://www.dbpedia.org/ontology/coordinates>" ],
      [ "point", "28.41861111111111 -81.58111111111111", "<http://www.georss.org/georss/point>" ], 
      [ "subject", "1971 establishments, Buildings and structures in Osceo...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Amusement Parks In Florida, Disney Parks And Attract ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Forbidden City", 
      [ "comment", "The Forbidden City was the Chinese imperial palace from ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "extension", "2004", "<http://dbpedia.org/property/extension>" ], 
      [ "geometry", "POINT(116.391 39.9147)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "coordinates", "39deg 54min 53sec N, 116deg 23min 26sec E", "<http://www.dbpedia.org/ontology/coordinates>" ],
      [ "label", "Forbidden City", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "point", "39.914722222222224 116.39055555555555", "<http://www.georss.org/georss/point>" ], 
      [ "region", "List of World Heritage Sites in Asia", "<http://dbpedia.org/property/region>" ], 
      [ "session", "11", "<http://dbpedia.org/property/session>" ], 
      [ "subject", "1406 establishments, 1420s architecture, 15th-century...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Cultural, Feature, Location Underspecified, Museums In ...", "<http://dbpedia.org/property/type>" ], 
      [ "whs", "Imperial Palaces of the Ming and Qing Dynasties in Bei...", "<http://dbpedia.org/property/whs>" ], 
      [ "wordnet type", "synset-monument-noun-2", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "year", "1987", "<http://dbpedia.org/property/year>" ], 
    ],
    [ "Statue of Liberty", 
      [ "beginning Date", "1886-10-28", "<http://dbpedia.org/property/beginningDate>" ], 
      [ "beginning Label", "Dedicated", "<http://dbpedia.org/property/beginningLabel>" ], 
      [ "comment", "The Statue of Liberty is a colossal neoclassical sculpt...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "governing Body", "National Park Service, United States", "<http://dbpedia.org/property/governingBody>" ], 
      [ "label", "Statue of Liberty", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "coordinates", "51.519459deg N 0.126931deg W", "http://dbpedia.org/ontology/coordinates>" ],
      [ "location", "Liberty Island, New York City, New York, U.S.", "<http://dbpedia.org/property/location>" ], 
      [ "locmapin", "New York City", "<http://dbpedia.org/property/locmapin>" ], 
      [ "sculptor", "Frederic Auguste Bartholdi", "<http://dbpedia.org/property/sculptor>" ], 
      [ "subject", "1886 in international relations, 1886 in the United ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "Articles related to the Statue of Liberty, Statue of Liberty", "<http://dbpedia.org/property/title>" ], 
      [ "visitation Num", "3200000", "<http://dbpedia.org/property/visitationNum>" ], 
      [ "visitation Year", "2009", "<http://dbpedia.org/property/visitationYear>" ], 
      [ "wordnet type", "synset-monument-noun-2", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "British Museum", 
      [ "area", "94, in", "<http://dbpedia.org/property/area>" ], 
      [ "collection", "8 million objects", "<http://dbpedia.org/ontology/collection>" ], 
      [ "comment", "The British Museum, in London, is widely considered to ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "established", "1753", "<http://dbpedia.org/property/established>" ], 
      [ "geometry", "POINT(-0.126931 51.5195)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "British Museum", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "coordinates", "40deg 41min 21sec N 74deg 2min 40sec W", "http://dbpedia.org/ontology/coordinates>" ],
      [ "location", "England, Great Russell Street, Great Russell Street, Lon...", "<http://dbpedia.org/ontology/location>" ], 
      [ "visitors", "6,049,000", "<http://dbpedia.org/ontology/numberOfVisitors>" ], 
      [ "point", "51.519459 -0.126931", "<http://www.georss.org/georss/point>" ], 
      [ "subject", "1753 establishments in Great Britain, ASEMUS museums, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Archaeology Museums In The United Kingdom, Architectural ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Smithsonian Institution", 
      [ "comment", "The Smithsonian Institution is an educational and res...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "established", "1846-08-10", "<http://dbpedia.org/property/established>" ], 
      [ "founding Date", "1846-08-10", "<http://dbpedia.org/ontology/foundingDate>" ], 
      [ "geometry", "POINT(-77.026 38.8888)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "Smithsonian Institution", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "location", "Washington, D. C.", "<http://dbpedia.org/ontology/location>" ],
      [ "coordinates", "38deg 53sec 19.68min N, 77deg 1min 33.6sec W", "http://dbpedia.org/ontology/coordinates>" ],
      [ "point", "38.8888 -77.026", "<http://www.georss.org/georss/point>" ], 
      [ "publictransit", "Smithsonian, L'Enfant Plaza Maryland Avenue exit.", "<http://dbpedia.org/property/publictransit>" ], 
      [ "secretary", "G. Wayne Clough", "<http://dbpedia.org/property/secretary>" ], 
      [ "subject", "1846 establishments in the United States, History of ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Architectural Structure, Building, Cornerstone Struct...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Graceland", 
      [ "added", "1991-11-07", "<http://dbpedia.org/property/added>" ], 
      [ "architect", "Furbringer & Ehrman", "<http://dbpedia.org/property/architect>" ], 
      [ "architecture", "Classical Revival", "<http://dbpedia.org/property/architecture>" ], 
      [ "area", "54984.7", "<http://dbpedia.org/ontology/area>" ], 
      [ "coordinates", "35deg 2min 46sec N 90deg 1min 23sec W", "http://dbpedia.org/ontology/coordinates>" ],      
      [ "built", "1939", "<http://dbpedia.org/property/built>" ], 
      [ "comment", "Graceland is a large white-columned mansion and ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "geometry", "POINT(-90.0231 35.0461)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "Graceland", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "locmap Label", "Graceland", "<http://dbpedia.org/property/locmapLabel>" ], 
      [ "locmapin", "Tennessee", "<http://dbpedia.org/property/locmapin>" ], 
      [ "subject", "Biographical museums in Tennessee, Buildings and struct...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Architectural Structure, Biographical Museums...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-location-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "Constructed", "1939", "<http://dbpedia.org/ontology/yearOfConstruction>" ], 
    ],
    [ "Arc de Triomphe", 
      [ "alternate Names", "Arc de Triomphe de l'Etoile", "<http://dbpedia.org/property/alternateNames>" ], 
      [ "architect", "Jean Chalgrin, Louis-Etienne Huricart de Thury", "<http://dbpedia.org/property/architect>" ], 
      [ "style", "Neoclassicism", "<http://dbpedia.org/property/architecturalStyle>" ], 
      [ "build Start", "1806-08-15", "<http://dbpedia.org/ontology/buildingStartDate>" ], 
      [ "coordinates", "48.8738deg N 2.2950deg E", "http://dbpedia.org/ontology/coordinates>" ],       
      [ "building Type", "Triumphal arch", "<http://dbpedia.org/property/buildingType>" ], 
      [ "comment", "The Arc de Triomphe (Arc de Triomphe de l'Etoile) is ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "geometry", "POINT(2.295 48.8738)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "inauguration Date", "29", "<http://dbpedia.org/property/inaugurationDate>" ], 
      [ "label", "Arc de Triomphe", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "location", "Place Charles de Gaulle", "<http://dbpedia.org/ontology/location>" ], 
      [ "opening Date", "1836-07-29", "<http://dbpedia.org/ontology/openingDate>" ], 
      [ "other Dimensions", "Deep:, Wide:", "<http://dbpedia.org/property/otherDimensions>" ], 
      [ "point", "48.8738 2.295", "<http://www.georss.org/georss/point>" ], 
      [ "start Date", "15", "<http://dbpedia.org/property/startDate>" ], 
      [ "subject", "16th arrondissement of Paris, 17th arrondissement of ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Architectural Structure, Building, Feature, Geoclass ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Empire State Building", 
      [ "architect", "Shreve, Lamb and Harmon", "<http://dbpedia.org/ontology/architect>" ], 
      [ "building Type", "Office, observation", "<http://dbpedia.org/property/buildingType>" ], 
      [ "comment", "The Empire State Building is a 102-story skyscraper loc...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "coordinates", "40deg 44min 54.36sec N 73deg 59min 08.36sec W", "http://dbpedia.org/ontology/coordinates>" ],        
      [ "completion Date", "1931", "<http://dbpedia.org/property/completionDate>" ], 
      [ "developer", "John J. Raskob", "<http://dbpedia.org/property/developer>" ], 
      [ "elevator Count", "73", "<http://dbpedia.org/property/elevatorCount>" ], 
      [ "floor Count", "102", "<http://dbpedia.org/ontology/floorCount>" ], 
      [ "geometry", "POINT(-73.9857 40.7484)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "Empire State Building", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "main Contractor", "Starrett Brothers and Eken", "<http://dbpedia.org/property/mainContractor>" ], 
      [ "point", "40.74843333333333 -73.98565555555555", "<http://www.georss.org/georss/point>" ], 
      [ "start Date", "1929", "<http://dbpedia.org/property/startDate>" ], 
      [ "Engineer", "Homer Gage Balcom", "<http://dbpedia.org/property/structuralEngineer>" ], 
      [ "subject", "Art Deco architecture in New York City, Art Deco sky...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title", "List of tallest buildings and structures in the world, ...", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Architectural Structure, Art Deco Buildings In New York ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-location-noun-1, synset-skyscraper-noun-1", "<http://dbpedia.org/property/wordnet_type>" ], 
      [ "years", "1931", "<http://dbpedia.org/property/years>" ], 
    ],
    [ "Great Wall of China", 
      [ "building Type", "Fortification", "<http://dbpedia.org/property/buildingType>" ], 
      [ "comment", "The Great Wall of China is a series of fortifications ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "coordinates", "40deg 40min 36.95sec N, 117deg 13min 54.95sec E", "<http://dbpedia.org/property/coordinates>" ], 
      [ "country", "China, Mongolia", "<http://dbpedia.org/ontology/country>" ], 
      [ "iso Region", "CN", "<http://dbpedia.org/property/isoRegion>" ], 
      [ "label", "Great Wall of China", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "latitude", "41", "<http://dbpedia.org/property/latitude>" ], 
      [ "location Country", "China", "<http://dbpedia.org/property/locationCountry>" ], 
      [ "pinyin", "Changcheng, Wanli Changcheng", "<http://dbpedia.org/property/p>" ], 
      [ "subject", "Chinese architectural history, Great Wall of China, Mega...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Architectural Structure, Building, Fortification, Loc...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "wordnet type", "synset-monument-noun-2", "<http://dbpedia.org/property/wordnet_type>" ], 
    ],
    [ "The Louvre", 
      [ "comment", "The Musee du Louvre, in English, the Louvre Mu...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "curator", "Marie-Laure de Rochebrune", "<http://dbpedia.org/property/curator>" ], 
      [ "director", "Henri Loyrette", "<http://dbpedia.org/property/director>" ], 
      [ "coordinates", "48.860339deg N 2.337599deg E", "<http://dbpedia.org/property/coordinates>" ], 
      [ "established", "1793", "<http://dbpedia.org/property/established>" ], 
      [ "geometry", "POINT(2.3376 48.8603)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "label", "Musee du Louvre", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "location", "75001, Palais Royal, Musee du Louvre,", "<http://dbpedia.org/property/location>" ], 
      [ "point", "48.860339 2.337599", "<http://www.georss.org/georss/point>" ], 
      [ "publictransit", "Palais Royal, Musee du Louvre 15px 15px 15px...", "<http://dbpedia.org/property/publictransit>" ], 
      [ "subject", "1793 establishments in France, Archaeological museums...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Archaeological Museums In France, Architectural Struct...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
      [ "visitors", "8,800,000", "<http://dbpedia.org/ontology/numberOfVisitors>" ], 
    ],
    [ "Reunification Palace", 
      [ "address", "135 Nam Ky Khoi Nghia Str, District 1, Ho Chi Min City...", "<http://dbpedia.org/property/address>" ], 
      [ "architect", "Ngo Viet Thu", "<http://dbpedia.org/property/architect>" ], 
      [ "coordinates", "10deg 46min 37sec N, 106deg 41min 43sec E", "<http://dbpedia.org/property/coordinates>" ], 
      [ "build End", "1966-10-31", "<http://dbpedia.org/ontology/buildingEndDate>" ], 
      [ "build Start", "1962-07-01", "<http://dbpedia.org/ontology/buildingStartDate>" ], 
      [ "building Type", "former presidential palace", "<http://dbpedia.org/property/buildingType>" ], 
      [ "Engineer", "Phan Van Dien", "<http://dbpedia.org/property/civilEngineer>" ], 
      [ "comment", "Reunification Palace (Vietnamese: Dinh Thong Nhat)...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "floor Count", "4", "<http://dbpedia.org/ontology/floorCount>" ], 
      [ "geometry", "POINT(106.695 10.7769)", "<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>" ], 
      [ "long", "106.695", "<http://www.w3.org/2003/01/geo/wgs84_pos#long>" ], 
      [ "point", "10.776944444444444 106.69527777777778", "<http://www.georss.org/georss/point>" ], 
      [ "subject", "Buildings and structures completed in 1966, Buildings ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Architectural Structure, Building, Building102913152, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
  ],
  [
    [ "Pineapple", 
      [ "binomial", "Ananas comosus", "<http://dbpedia.org/property/binomial>" ], 
      [ "carbs", "12.63", "<http://dbpedia.org/property/carbs>" ], 
      [ "class", "Monocotyledon", "<http://dbpedia.org/ontology/class>" ], 
      [ "comment", "Pineapple (Ananas comosus), a tropical plant with ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "division", "Flowering plant", "<http://dbpedia.org/ontology/division>" ], 
      [ "familia", "Bromeliaceae", "<http://dbpedia.org/property/familia>" ], 
      [ "genus", "Ananas", "<http://dbpedia.org/ontology/genus>" ], 
      [ "kingdom", "Plant", "<http://dbpedia.org/ontology/kingdom>" ], 
      [ "kj", "202", "<http://dbpedia.org/property/kj>" ], 
      [ "label", "Pineapple", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order", "Commelinids, Poales", "<http://dbpedia.org/ontology/order>" ], 
      [ "species", "A. comosus", "<http://dbpedia.org/property/species>" ], 
      [ "subfamilia", "Bromelioideae", "<http://dbpedia.org/property/subfamilia>" ], 
      [ "subject", "Ananas, Crops originating from the Americas, Flora of ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "synonym", "Ananas sativus", "<http://dbpedia.org/ontology/synonym>" ], 
      [ "type", "Biological Living Object, Eukaryote, Eukaryotic Cell, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Carrot", 
      [ "betacarotene Ug", "8285", "<http://dbpedia.org/property/betacaroteneUg>" ], 
      [ "binomial", "Daucus carota", "<http://dbpedia.org/property/binomial>" ], 
      [ "carbs", "9.0", "<http://dbpedia.org/property/carbs>" ], 
      [ "class", "Eudicots", "<http://dbpedia.org/ontology/class>" ], 
      [ "comment", "The carrot is a root vegetable, usually orange in col...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "division", "Flowering plant", "<http://dbpedia.org/ontology/division>" ], 
      [ "familia", "Apiaceae", "<http://dbpedia.org/property/familia>" ],
      [ "genus", "Daucus", "<http://dbpedia.org/ontology/genus>" ], 
      [ "kingdom", "Plant", "<http://dbpedia.org/ontology/kingdom>" ], 
      [ "kj", "173", "<http://dbpedia.org/property/kj>" ], 
      [ "label", "Carrot", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order", "Apiales, Asterids", "<http://dbpedia.org/ontology/order>" ], 
      [ "species", "D. carota", "<http://dbpedia.org/property/species>" ], 
      [ "subject", "Edible Apiaceae, Plants and pollinators, Root vegetables", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Biological Living Object, Eukaryote, Eukaryotic Cell, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Apple", 
      [ "binomial", "Malus domestica", "<http://dbpedia.org/property/binomial>" ], 
      [ "carbs", "13.81", "<http://dbpedia.org/property/carbs>" ], 
      [ "class", "Eudicots", "<http://dbpedia.org/ontology/class>" ], 
      [ "comment", "The apple is the pomaceous fruit of the apple tree, ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "division", "Flowering plant", "<http://dbpedia.org/ontology/division>" ], 
      [ "familia", "Rosaceae", "<http://dbpedia.org/property/familia>" ], 
      [ "genus", "Malus", "<http://dbpedia.org/ontology/genus>" ], 
      [ "kingdom", "Plant", "<http://dbpedia.org/ontology/kingdom>" ], 
      [ "kj", "218", "<http://dbpedia.org/property/kj>" ], 
      [ "label", "Apple", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "order", "Rosales, Rosids", "<http://dbpedia.org/ontology/order>" ], 
      [ "species", "M. domestica, Malus domestica", "<http://dbpedia.org/property/species>" ], 
      [ "subfamilia", "Maloideae or Spiraeoideae", "<http://dbpedia.org/property/subfamilia>" ], 
      [ "subject", "Apples, Maleae, Sequenced genomes", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "Biological Living Object, Eukaryote, Eukaryotic Cell, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
  ],
  [
    [ "The Lord of the Rings", 
      [ "author", "J. R. R. Tolkien", "<http://dbpedia.org/property/author>" ], 
      [ "books", "The Fellowship of the Ring, The Return of the King, ...", "<http://dbpedia.org/property/books>" ], 
      [ "comment", "The Lord of the Rings is an epic high fantasy novel writ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "England", "<http://dbpedia.org/property/country>" ], 
      [ "genre", "Adventure novel, High fantasy", "<http://dbpedia.org/property/genre>" ], 
      [ "label", "The Lord of the Rings", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "media Type", "Print", "<http://dbpedia.org/property/mediaType>" ], 
      [ "pages", "1216", "<http://dbpedia.org/property/pages>" ], 
      [ "preceded By", "The Hobbit", "<http://dbpedia.org/property/precededBy>" ], 
      [ "publisher", "Allen & Unwin", "<http://dbpedia.org/property/publisher>" ], 
      [ "subject", "1950s fantasy novels, 1954 novels, British fantasy ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1954Novels, English Novels, High Fantasy Novels", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "The Little Prince", 
      [ "author", "Antoine de Saint- Exupery", "<http://dbpedia.org/property/author>" ], 
      [ "comment", "The Little Prince (French: Le Petit Prince) is a ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "France, United States, The first English trans...", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "Antoine de Saint-Exupery", "<http://dbpedia.org/ontology/coverArtist>" ], 
      [ "followed By", "Lettre a un otage", "<http://dbpedia.org/property/followedBy>" ], 
      [ "illustrator", "Antoine de Saint-Exupery", "<http://dbpedia.org/ontology/illustrator>" ], 
      [ "label", "The Little Prince", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "French, English and dialects.", "<http://dbpedia.org/property/language>" ], 
      [ "media Type", "Ballet, Compact Cassette, Compact Disc, E-book, Film...", "<http://dbpedia.org/ontology/mediaType>" ], 
      [ "preceded By", "Flight to Arras", "<http://dbpedia.org/property/precededBy>" ], 
      [ "previous Work", "Flight to Arras", "<http://dbpedia.org/ontology/previousWork>" ], 
      [ "publisher", "Gallimard, Reynal & Hitchcock", "<http://dbpedia.org/ontology/publisher>" ], 
      [ "release Date", "1943, 1945", "<http://dbpedia.org/property/releaseDate>" ], 
      [ "subject", "1943 novels, Antoine de Saint- Exupery, Aviation novels...", "<http://purl.org/dc/terms/subject>" ], 
      [ "title Orig", "Le Petit Prince", "<http://dbpedia.org/property/titleOrig>" ], 
      [ "type", "1943Novels, Book, Book CW, Creative Work, Fictional ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Anne of Green Gables", 
      [ "author", "Lucy Maud Montgomery", "<http://dbpedia.org/property/author>" ], 
      [ "comment", "Anne of Green Gables (1908) is a bestselling novel by Can...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United States", "<http://dbpedia.org/property/country>" ], 
      [ "followed By", "Anne of Avonlea", "<http://dbpedia.org/property/followedBy>" ], 
      [ "genre", "Novel", "<http://dbpedia.org/property/genre>" ], 
      [ "illustrator", "M. A. and W. A. J. Claus", "<http://dbpedia.org/property/illustrator>" ], 
      [ "isbn", "N/A", "<http://dbpedia.org/ontology/isbn>" ], 
      [ "label", "Anne of Green Gables", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English language", "<http://dbpedia.org/ontology/language>" ], 
      [ "literary Genre", "Novel", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Hardcover, Print", "<http://dbpedia.org/ontology/mediaType>" ], 
      [ "pages", "429", "<http://dbpedia.org/property/pages>" ], 
      [ "publisher", "L. C. Page & Co.", "<http://dbpedia.org/property/publisher>" ], 
      [ "release Date", "June 1908", "<http://dbpedia.org/property/releaseDate>" ], 
      [ "subject", "1908 novels, Anne of Green Gables books, Canadian ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "subsequent Work", "Anne of Avonlea", "<http://dbpedia.org/ontology/subsequentWork>" ], 
      [ "type", "1908 Novels, Book, Book CW, Creative Work, Novels By ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "The Catcher in the Rye", 
      [ "author", "J. D. Salinger", "<http://dbpedia.org/ontology/author>" ], 
      [ "comment", "The Catcher in the Rye is a 1951 novel by J. D. Saling...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United States", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "E. Michael Mitchell", "<http://dbpedia.org/property/coverArtist>" ], 
      [ "genre", "Novel", "<http://dbpedia.org/property/genre>" ], 
      [ "isbn", "0-316-76953-3", "<http://dbpedia.org/property/isbn>" ], 
      [ "label", "The Catcher in the Rye", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English language", "<http://dbpedia.org/property/language>" ], 
      [ "literary Genre", "Novel", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Hardcover, Print", "<http://dbpedia.org/ontology/mediaType>" ], 
      [ "number Of Pages", "214", "<http://dbpedia.org/ontology/numberOfPages>" ], 
      [ "oclc", "287628", "<http://dbpedia.org/property/oclc>" ], 
      [ "publisher", "Little, Brown and Company", "<http://dbpedia.org/ontology/publisher>" ], 
      [ "subject", "1949 in fiction, 1951 novels, American novels, Debut...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1951Novels, American Novels, Book, Book CW, Creative ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "Dream of the Red Chamber", 
      [ "author", "Cao Xueqin", "<http://dbpedia.org/property/author>" ], 
      [ "comment", "Dream of the Red Chamber, composed by Cao Xueqin, is ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "China", "<http://dbpedia.org/ontology/country>" ], 
      [ "genre", "Novel", "<http://dbpedia.org/property/genre>" ], 
      [ "label", "Dream of the Red Chamber", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "Chinese language", "<http://dbpedia.org/property/language>" ], 
      [ "literary Genre", "Novel", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Scribal copies/Print", "<http://dbpedia.org/property/mediaType>" ], 
      [ "pinyin", "Hong Lou Meng", "<http://dbpedia.org/property/p>" ], 
      [ "subject", "18th-century novels, Chinese classic novels, Chinese ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "18th-century Novels, Book, Book CW, Chinese Classic ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "The Da Vinci Code", 
      [ "author", "Dan Brown", "<http://dbpedia.org/ontology/author>" ], 
      [ "comment", "The Da Vinci Code is a 2003 mystery-detective novel ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "congress", "PS3552.R685434 D3 2003", "<http://dbpedia.org/property/congress>" ], 
      [ "country", "United Kingdom, United States", "<http://dbpedia.org/ontology/country>" ], 
      [ "dewey", "813.54 21", "<http://dbpedia.org/property/dewey>" ], 
      [ "followed By", "The Lost Symbol", "<http://dbpedia.org/property/followedBy>" ], 
      [ "genre", "Conspiracy fiction, Detective fiction, Mystery fiction, ...", "<http://dbpedia.org/property/genre>" ], 
      [ "isbn", "0-385-50420-9 (US) / 9780552159715 (UK)", "<http://dbpedia.org/property/isbn>" ], 
      [ "label", "The Da Vinci Code", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "literary Genre", "Conspiracy fiction, Detective fiction, Mystery ...", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "number Of Pages", "359, 454, 489, 583", "<http://dbpedia.org/ontology/numberOfPages>" ], 
      [ "oclc", "50920659", "<http://dbpedia.org/ontology/oclc>" ], 
      [ "pages", "359", "<http://dbpedia.org/property/pages>" ], 
      [ "previous Work", "Angels & Demons", "<http://dbpedia.org/ontology/previousWork>" ], 
      [ "publisher", "Bantam Books, Doubleday (publisher), Transworld Publi...", "<http://dbpedia.org/ontology/publisher>" ], 
      [ "subject", "2003 novels, Albinism in popular culture, American ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "subsequent Work", "The Lost Symbol", "<http://dbpedia.org/ontology/subsequentWork>" ], 
      [ "type", "2003Novels, American Crime Novels, American Mystery ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "A Tale of Two Cities", 
      [ "author", "Charles Dickens", "<http://dbpedia.org/ontology/author>" ], 
      [ "comment", "A Tale of Two Cities is a novel by Charles Dickens, set ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United Kingdom", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "Hablot Knight Browne", "<http://dbpedia.org/property/coverArtist>" ], 
      [ "genre", "Novel, Historical, Social criticism", "<http://dbpedia.org/property/genre>" ], 
      [ "illustrator", "Hablot Knight Browne", "<http://dbpedia.org/property/illustrator>" ], 
      [ "label", "A Tale of Two Cities", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "literary Genre", "Historical novel, Novel, Social criticism", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Print", "<http://dbpedia.org/property/mediaType>" ], 
      [ "pub Date", "1859", "<http://dbpedia.org/property/pubDate>" ], 
      [ "publisher", "Chapman & Hall, London: Chapman & Hall", "<http://dbpedia.org/ontology/publisher>" ], 
      [ "subject", "1859 novels, British novels, Novels by Charles Dickens, ...", "<http://purl.org/dc/terms/subject>" ], 
      [ "type", "1859Novels, Book, Book CW, British Novels, Creative ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "The Hobbit", 
      [ "author", "J. R. R. Tolkien", "<http://dbpedia.org/ontology/author>" ], 
      [ "comment", "The Hobbit, or There and Back Again, better known by ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United Kingdom", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "J. R. R. Tolkien", "<http://dbpedia.org/ontology/coverArtist>" ], 
      [ "followed By", "The Lord of the Rings", "<http://dbpedia.org/property/followedBy>" ], 
      [ "genre", "Children's literature, Juvenile fantasy", "<http://dbpedia.org/property/genre>" ], 
      [ "illustrator", "J. R. R. Tolkien", "<http://dbpedia.org/ontology/illustrator>" ], 
      [ "isbn", "n/a", "<http://dbpedia.org/ontology/isbn>" ], 
      [ "label", "The Hobbit, or There and Back Again", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "literary Genre", "Children's literature, Juvenile fantasy", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Print", "<http://dbpedia.org/property/mediaType>" ], 
      [ "number Of Pages", "310", "<http://dbpedia.org/ontology/numberOfPages>" ], 
      [ "publisher", "Allen & Unwin", "<http://dbpedia.org/property/publisher>" ], 
      [ "release Date", "21", "<http://dbpedia.org/property/releaseDate>" ], 
      [ "subject", "1930s fantasy novels, 1937 novels, British fantasy nov...", "<http://purl.org/dc/terms/subject>" ], 
      [ "subsequent Work", "The Lord of the Rings", "<http://dbpedia.org/ontology/subsequentWork>" ], 
      [ "type", "1937 Novels, Book, Book CW, British Novels, Creative ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "And Then There Were None", 
      [ "author", "Agatha Christie", "<http://dbpedia.org/ontology/author>" ], 
      [ "comment", "And Then There Were None is a detective fiction novel ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "country", "United Kingdom", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "Stephen Bellman", "<http://dbpedia.org/property/coverArtist>" ], 
      [ "followed By", "Sad Cypress", "<http://dbpedia.org/property/followedBy>" ], 
      [ "genre", "Crime fiction", "<http://dbpedia.org/property/genre>" ], 
      [ "isbn", "978-0-00-713683-4", "<http://dbpedia.org/property/isbn>" ], 
      [ "label", "And Then There Were None", "<http://www.w3.org/2000/01/rdf-schema#label>" ], 
      [ "language", "English", "<http://dbpedia.org/property/language>" ], 
      [ "literary Genre", "Crime fiction", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Hardcover, Print", "<http://dbpedia.org/ontology/mediaType>" ], 
      [ "pages", "256", "<http://dbpedia.org/property/pages>" ], 
      [ "preceded By", "The Regatta Mystery", "<http://dbpedia.org/property/precededBy>" ], 
      [ "previous Work", "The Regatta Mystery", "<http://dbpedia.org/ontology/previousWork>" ], 
      [ "publisher", "Collins Crime Club", "<http://dbpedia.org/property/publisher>" ], 
      [ "subject", "1939 novels, Novels by Agatha Christie, Novels first pub...", "<http://purl.org/dc/terms/subject>" ], 
      [ "subsequent Work", "Sad Cypress", "<http://dbpedia.org/ontology/subsequentWork>" ], 
      [ "type", "1939Novels, 1943Plays, Book, Book CW, Creative Work, ...", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
    [ "The Lion, the Witch and the Wardrobe", 
      [ "author", "C. S. Lewis", "<http://dbpedia.org/property/author>" ], 
      [ "comment", "The Lion, the Witch and the Wardrobe is a high fantasy ...", "<http://www.w3.org/2000/01/rdf-schema#comment>" ], 
      [ "congress", "PZ7.L58474 Li 1994", "<http://dbpedia.org/property/congress>" ], 
      [ "country", "United Kingdom", "<http://dbpedia.org/property/country>" ], 
      [ "cover Artist", "Pauline Baynes", "<http://dbpedia.org/ontology/coverArtist>" ], 
      [ "dewey", "Fic 20", "<http://dbpedia.org/property/dewey>" ], 
      [ "followed By", "Prince Caspian", "<http://dbpedia.org/property/followedBy>" ], 
      [ "genre", "Children's literature, Fantasy", "<http://dbpedia.org/property/genre>" ], 
      [ "illustrator", "Pauline Baynes", "<http://dbpedia.org/ontology/illustrator>" ], 
      [ "isbn", "ISBN 0-06-023481-4 (modern hardcover)", "<http://dbpedia.org/property/isbn>" ], 
      [ "language", "English language", "<http://dbpedia.org/ontology/language>" ], 
      [ "literary Genre", "Children's literature, Fantasy", "<http://dbpedia.org/ontology/literaryGenre>" ], 
      [ "media Type", "Hardcover, Paperback, Print", "<http://dbpedia.org/ontology/mediaType>" ], 
      [ "number Of Pages", "208", "<http://dbpedia.org/ontology/numberOfPages>" ], 
      [ "oclc", "28291231", "<http://dbpedia.org/ontology/oclc>" ], 
      [ "pages", "208", "<http://dbpedia.org/property/pages>" ], 
      [ "publisher", "Geoffrey Bles", "<http://dbpedia.org/property/publisher>" ], 
      [ "series", "The Chronicles of Narnia", "<http://dbpedia.org/ontology/series>" ], 
      [ "subject", "1950 novels, 1950s fantasy novels, British children...", "<http://purl.org/dc/terms/subject>" ], 
      [ "subsequent Work", "Prince Caspian", "<http://dbpedia.org/ontology/subsequentWork>" ], 
      [ "title", "The Lion, the Witch and the Wardrobe", "<http://dbpedia.org/property/title>" ], 
      [ "type", "Book, Book CW, Creative Work, Thing, Work, Written Work", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" ], 
    ],
  ],
];
