// types: 1 = related, 2 = redundant
var questions = [
  { id:0, type:2, subject:'Patea (town)',
    predicate1:'comment', object1:'Patea is the third-largest town in South Taranaki, New Zealand...',
    predicate2:'thumbnail', object2:'http://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Patea,_Taranaki,_New_Zealand...',
    algorithm:'Redundant', expectedvalue:'0' },
  { id:1, type:2, subject:'Patea (town)',
    predicate1:'lattitudeMinutes', object1:'45',
    predicate2:'name', object2:'Patea',
    algorithm:'Redundant', expectedvalue:'0' },
  { id:2, type:2, subject:'Patea (town)',
    predicate1:'subject', object1:'Category:South Taranaki District',
    predicate2:'lattitudeSeconds', object2:'26',
    algorithm:'Redundant', expectedvalue:'0' },
  { id:3, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'birthYear', object1:'1946-01-01 00:00:00',
    predicate2:'birthDate', object2:'1946-12-18',
    algorithm:'Redundant', expectedvalue:'0.38888888888888884' },
  { id:4, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'alternativeNames', object1:'Steven Allan Spielberg, Stephen Spielberg',
    predicate2:'surname', object2:'Spielberg',
    algorithm:'Redundant', expectedvalue:'0.5' },
  { id:5, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'shortDescription', object1:'Academy Award winning American film director and producer',
    predicate2:'occupation', object2:'Film director, producer, screenwriter',
    algorithm:'Redundant', expectedvalue:'0.44680851063829785' },
  { id:6, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'description', object1:'Academy Award-winning American film director and producer',
    predicate2:'shortDescription', object2:'Academy Award winning American film director and producer',
    algorithm:'Redundant', expectedvalue:'1' },
  { id:7, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'name', object1:'Steven Spielberg',
    predicate2:'birthName', object2:'Steven Allan Spielberg',
    algorithm:'Redundant', expectedvalue:'1' },
  { id:8, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'name', object1:'Steven Spielberg',
    predicate2:'birthName', object2:'Steven Allan Spielberg',
    algorithm:'Redundant', expectedvalue:'1' },
  { id:9, type:2, subject:'Steven Spielberg (filmmaker)',
    predicate1:'name', object1:'Steven Spielberg',
    predicate2:'surname', object2:'Spielberg',
    algorithm:'Redundant', expectedvalue:'1' },
  { id:10, type:1, subject:'Athens (city)',
    predicate1:'country', object1:'Greece',
    predicate2:'aprLowC', object2:'10',
    algorithm:'DiceAvg', expectedvalue:'0' },
  { id:11, type:1, subject:'The Beatles',
    predicate1:'activeYearsEndYear', object1:'1970-01-01 00:00:00',
    predicate2:'pastMembers', object2:'Pete Best',
    algorithm:'DiceAvg', expectedvalue:'0.037037037037037035' },
  { id:12, type:1, subject:'Steven Spielberg (filmmaker)',
    predicate1:'wikiPageExternalLink', object1:'http://www.empireonline.com/features/spielbergat60/60.asp',
    predicate2:'birthYear', object2:'1946-01-01 00:00:00',
    algorithm:'DiceAvg', expectedvalue:'0' },
  { id:13, type:1, subject:'Patea (town)',
    predicate1:'subdivisionType', object1:'District',
    predicate2:'subdivisionType', object2:'Country',
    algorithm:'DiceAvg', expectedvalue:'0.5769230769230769' },
  { id:14, type:1, subject:'Patea (town)',
    predicate1:'longitude', object1:'174.4766693115234',
    predicate2:'longitudeDegrees', object2:'174',
    algorithm:'DiceAvg', expectedvalue:'0.45893719806763283' },
  { id:15, type:1, subject:'Barbie (doll)',
    predicate1:'name', object1:'Barbara Milli Roberts',
    predicate2:'surname', object2:'Roberts',
    algorithm:'DiceAvg', expectedvalue:'0.5641025641025641' },
  { id:16, type:1, subject:'Peter Jackson (filmmaker)',
    predicate1:'name', object1:'Sir Peter Jackson',
    predicate2:'name', object2:'Jackson, Peter',
    algorithm:'DiceAvg', expectedvalue:'0.8793103448275862' },
  { id:17, type:1, subject:'Peter Jackson (filmmaker)',
    predicate1:'name', object1:'Peter Jackson',
    predicate2:'name', object2:'Jackson, Peter',
    algorithm:'DiceAvg', expectedvalue:'0.9' },
  { id:18, type:1, subject:'Steven Spielberg (filmmaker)',
    predicate1:'name', object1:'Steven Spielberg',
    predicate2:'name', object2:'Spielberg, Steven',
    algorithm:'DiceAvg', expectedvalue:'0.9516129032258065' },
  { id:19, type:1, subject:'Peter Jackson (filmmaker)',
    predicate1:'name', object1:'Peter Jackson',
    predicate2:'name', object2:'Sir Peter Jackson',
    algorithm:'DiceAvg', expectedvalue:'0.9285714285714286' },
  { id:20, type:1, subject:'Patea (town)',
    predicate1:'subject', object1:'Category:South Taranaki District',
    predicate2:'longitudeDegrees', object2:'174',
    algorithm:'DiceMax', expectedvalue:'0' },
  { id:21, type:1, subject:'Patea (town)',
    predicate1:'longitude', object1:'174.4766693115234',
    predicate2:'subdivisionName', object2:'Taranaki Region',
    algorithm:'DiceMax', expectedvalue:'0.09090909090909091' },
  { id:22, type:1, subject:'Steven Spielberg (filmmaker)',
    predicate1:'networth', object1:'3.0E9',
    predicate2:'religion', object2:'Judaism',
    algorithm:'DiceMax', expectedvalue:'0' },
  { id:23, type:1, subject:'Patea (town)',
    predicate1:'Longitude East-West', object1:'E',
    predicate2:'longitudeSeconds', object2:'36',
    algorithm:'DiceMax', expectedvalue:'0.42424242424242425' },
  { id:24, type:1, subject:'Patea (town)',
    predicate1:'coordinatesDisplay', object1:'inline,title',
    predicate2:'coordinatesRegion', object2:'NZ',
    algorithm:'DiceMax', expectedvalue:'0.6060606060606061' },
  { id:25, type:1, subject:'Steven Spielberg (filmmaker)',
    predicate1:'label', object1:'Steven Spielberg',
    predicate2:'alternativeNames', object2:'Steven Allan Spielberg, Stephen Spielberg',
    algorithm:'DiceMax', expectedvalue:'0.5454545454545454' },
  { id:26, type:1, subject:'Patea (town)',
    predicate1:'subdivisionType', object1:'District',
    predicate2:'subdivisionType', object2:'Region',
    algorithm:'DiceMax', expectedvalue:'1' },
  { id:27, type:1, subject:'Patea (town)',
    predicate1:'subdivisionName', object1:'Taranaki Region',
    predicate2:'subdivisionName', object2:'New Zealand',
    algorithm:'DiceMax', expectedvalue:'1' },
  { id:28, type:1, subject:'Patea (town)',
    predicate1:'subject', object1:'Category:Populated places in New Zealand',
    predicate2:'subject', object2:'Category:South Taranaki District',
    algorithm:'DiceMax', expectedvalue:'1' },
  { id:29, type:1, subject:'Patea (town)',
    predicate1:'subdivisionName', object1:'South Taranaki District',
    predicate2:'subdivisionName', object2:'Taranaki Region',
    algorithm:'DiceMax', expectedvalue:'1' },
  { id:30, type:1, subject:'Patea (town)',
    predicate1:'comment', object1:'Patea is the third-largest town in South Taranaki, New Zealand...',
    predicate2:'populationTotal', object2:'1143',
    algorithm:'LevAvg', expectedvalue:'0.09999999999999998' },
  { id:31, type:1, subject:'Patea (town)',
    predicate1:'Longitude East-West', object1:'E',
    predicate2:'subdivisionName', object2:'Taranaki Region',
    algorithm:'LevAvg', expectedvalue:'0.05263157894736842' },
  { id:32, type:1, subject:'Patea (town)',
    predicate1:'country', object1:'New Zealand',
    predicate2:'longitudeSeconds', object2:'36',
    algorithm:'LevAvg', expectedvalue:'0.0625' },
  { id:33, type:1, subject:'Patea (town)',
    predicate1:'wikiPageExternalLink', object1:'http://www.stjospatea.school.nz',
    predicate2:'wikiPageExternalLink', object2:'http://72.14.253.104/search?q=cache:Ogv_p73ng-IJ:www.stdc.co.nz/pdf/patea...',
    algorithm:'LevAvg', expectedvalue:'0.611842105263158' },
  { id:34, type:1, subject:'Athens (city)',
    predicate1:'areaCode', object1:'21',
    predicate2:'areaUrban', object2:'412',
    algorithm:'LevAvg', expectedvalue:'0.3888888888888889' },
  { id:35, type:1, subject:'Patea (town)',
    predicate1:'subdivisionName', object1:'South Taranaki District',
    predicate2:'subdivisionType', object2:'Country',
    algorithm:'LevAvg', expectedvalue:'0.508695652173913' },
  { id:36, type:1, subject:'Peter Jackson (filmmaker)',
    predicate1:'name', object1:'Sir Peter Jackson',
    predicate2:'name', object2:'Peter Jackson',
    algorithm:'LevAvg', expectedvalue:'0.8823529411764706' },
  { id:37, type:1, subject:'Athens (city)',
    predicate1:'capitalOf', object1:'Greece',
    predicate2:'capital', object2:'Greece',
    algorithm:'LevAvg', expectedvalue:'0.8888888888888888' },
  { id:38, type:1, subject:'Oregon (state)',
    predicate1:'country', object1:'USA',
    predicate2:'incountry', object2:'USA',
    algorithm:'LevAvg', expectedvalue:'0.8888888888888888' },
  { id:39, type:1, subject:'Barbie (doll)',
    predicate1:'name', object1:'Barbara Millicent Roberts',
    predicate2:'name', object2:'Barbara Milli Roberts',
    algorithm:'LevAvg', expectedvalue:'0.9199999999999999' },
  { id:40, type:1, subject:'Patea (town)',
    predicate1:'wikiPageUsesTemplate', object1:'http://dbpedia.org/resource/Template:Infobox_settlement',
    predicate2:'longitudeSeconds', object2:'36',
    algorithm:'LevMax', expectedvalue:'0.09999999999999998' },
  { id:41, type:1, subject:'Patea (town)',
    predicate1:'country', object1:'New Zealand',
    predicate2:'wikiPageUsesTemplate', object2:'http://dbpedia.org/resource/Template:Infobox_settlement',
    algorithm:'LevMax', expectedvalue:'0.09090909090909094' },
  { id:42, type:1, subject:'Patea (town)',
    predicate1:'comment', object1:'Patea is the third-largest town in South Taranaki, New Zealand...',
    predicate2:'longitude', object2:'174.4766693115234',
    algorithm:'LevMax', expectedvalue:'0.11111111111111116' },
  { id:43, type:1, subject:'Athens (city)',
    predicate1:'aprPrecipitationMm', object1:'31',
    predicate2:'areaMunicipality', object2:'39',
    algorithm:'LevMax', expectedvalue:'0.5' },
  { id:44, type:1, subject:'Steven Spielberg (filmmaker)',
    predicate1:'birthName', object1:'Steven Allan Spielberg',
    predicate2:'birthYear', object2:'1946-01-01 00:00:00',
    algorithm:'LevMax', expectedvalue:'0.5555555555555556' },
  { id:45, type:1, subject:'Patea (town)',
    predicate1:'country', object1:'New Zealand',
    predicate2:'geometry', object2:'POINT(174.477 -39.7572)',
    algorithm:'LevMax', expectedvalue:'0.5' },
  { id:46, type:1, subject:'Patea (town)',
    predicate1:'label', object1:'Patea',
    predicate2:'name', object2:'Patea',
    algorithm:'LevMax', expectedvalue:'1' },
  { id:47, type:1, subject:'Patea (town)',
    predicate1:'country', object1:'New Zealand',
    predicate2:'subdivisionName', object2:'New Zealand',
    algorithm:'LevMax', expectedvalue:'1' },
  { id:48, type:1, subject:'Patea (town)',
    predicate1:'comment', object1:'Patea is the third-largest town in South Taranaki, New Zealand...',
    predicate2:'abstract', object2:'Patea is the third-largest town in South Taranaki, New Zealand...',
    algorithm:'LevMax', expectedvalue:'1' },
  { id:49, type:1, subject:'Patea (town)',
    predicate1:'label', object1:'Patea',
    predicate2:'name', object2:'Patea',
    algorithm:'LevMax', expectedvalue:'1' }
];
